### ISSUE TITLE
Please create a new release.

### ISSUE THREAD

**Issue by Joshua-Snapp** [tedivm/puppet-ghebackups#2]
Thanks for merging my pull request #1.

I'd like to continue using your original repo in my organization, rather than having to point to my fork. The thing is, we're trying to get better at locking to release tags of the repos we rely on.

Would you mind creating a new release of this repo? I was going to up the version in my forked metadata.json to 0.6.2. If not, I can always lock to a commit SHA or use my fork.

Thanks for your help!

**Comment by tedivm** [comment]
I just made a new release- enjoy!
